version: '3.8'
services:
  api-gateway:
    image: maianhhoang31072003/api-gateway:latest
    container_name: api-gateway
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8080:8080"


