spring:
  application:
    name: read-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.ecommerce.library.kafka.event.*"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:keycloak}:${KEYCLOAK_PORT:8080}/auth/realms/${KEYCLOAK_REALM:ecommerce}
  data:
    mongodb:
      uri: mongodb://read-service:read-service@${MONGODB_HOST:mongo}:${MONGODB_PORT:27017}/read-service
  elasticsearch:
    uris: http://${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}
    username: ${ELASTICSEARCH_USERNAME:elastic}
    password: ${ELASTICSEARCH_PASSWORD:changeme}
minio:
  url: http://${MINIO_HOST:host.docker.internal}:${MINIO_PORT:9000}
  url-public: ${MINIO_URL_PUBLIC:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:root}
  secret-key: ${MINIO_SECRET_KEY:password}
  bucket-name: ${MINIO_BUCKET_NAME:ecommerce}

server:
  port: ${SERVER_PORT:8086}

here:
  url: ${HERE_API_URL:https://geocode.search.hereapi.com/v1/geocode}
  api-key: ${HERE_API_KEY:mGVJd3sfQbBjNXCQ_GgvpAdwxWpHW-bvFeBo-9pDr3c}

ai-service:
  host: ${AI_SERVICE_HOST:ai-service}
  port: ${AI_SERVICE_PORT:8000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always