global:
  resolve_timeout: 5m

route:
  receiver: "telegram"
  group_wait: 5m
  group_interval: 10m
  repeat_interval: 1h
  group_by: ['alertname', 'severity']

receivers:
  - name: "telegram"
    telegram_configs:
      - bot_token: '8282766305:AAFinvMiQAw8fklPizJAe_PWw9cRmNv-CQw'
        chat_id: 7414147387
        parse_mode: 'HTML'
        message: |
          🚨 <b>{{ .Status | toUpper }}</b> 🚨
          
          {{ range .Alerts }}
          <b>Alert:</b> {{ .Labels.alertname }}
          <b>Severity:</b> {{ .Labels.severity }}
          <b>Summary:</b> {{ .Annotations.summary }}
          <b>Description:</b> {{ .Annotations.description }}
          <b>Started:</b> {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}
