version: '3.8'
services:
  product-service:
    image: maianhhoang31072003/product-service:latest
    container_name: product-service
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8085:8085"


