spring:
  application:
    name: saga-service
  grpc:
    client:
      channels:
        auth-service:
          address: ${AUTH_SERVICE_HOST:auth-service}:${AUTH_SERVICE_PORT:9092}
        user-service:
          address: ${USER_SERVICE_HOST:user-service}:${USER_SERVICE_PORT:9093}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:keycloak}:${KEYCLOAK_PORT:8080}/auth/realms/${KEYCLOAK_REALM:ecommerce}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  temporal:
    connection:
      target: ${TEMPORAL_HOST:temporal}:${TEMPORAL_PORT:7233}
    workers:
      - task-queue: createUserQueue
        workflow-classes:
          - com.ecommerce.saga.saga.workflow.impl.CreateUserWorkFlowImpl
        activity-beans:
          - createUserActivitiesImpl
      - task-queue: approveOwnerQueue
        workflow-classes:
          - com.ecommerce.saga.saga.workflow.impl.ApproveOwnerWorkFlowImpl
        activity-beans:
          - approveOwnerActivitiesImpl


server:
  port: ${SERVER_PORT:8088}
