spring:
  application:
    name: saga-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:keycloak}:${KEYCLOAK_PORT:8080}/auth/realms/${KEYCLOAK_REALM:ecommerce}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  temporal:
    connection:
      target: ${TEMPORAL_HOST:temporal}:${TEMPORAL_PORT:7233}
    workers:
      - task-queue: createUserQueue
        workflow-classes:
          - com.ecommerce.saga.saga.workflow.impl.CreateUserWorkFlowImpl
        activity-beans:
          - createUserActivitiesImpl
      - task-queue: approveOwnerQueue
        workflow-classes:
          - com.ecommerce.saga.saga.workflow.impl.ApproveOwnerWorkFlowImpl
        activity-beans:
          - approveOwnerActivitiesImpl


server:
  port: ${SERVER_PORT:8084}

eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_SERVICE_HOST:discovery-service}:${DISCOVERY_SERVICE_PORT:8761}/eureka/
