spring:
  application:
    name: chat-notification-service
  kafka:
    bootstrap-servers: localhost:19092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/auth/realms/ecommerce
  data:
    mongodb:
        uri: mongodb://chat-notification-service:chat-notification-service@localhost:27017/chat-notification-service
    redis:
      host: localhost
      port: 6379


server:
  port: 8082
minio:
  url: http://localhost:9000
  access-key: root
  secret-key: password
  bucket-name: ecommerce

web-push:
  vapid-private-key: bNjc8_tboWXoOZmzBt0EJxgmLJXkj8A34SkbOZxTVYk
  vapid-public-key: BEp-S9Fb6ObCba-w6hWdCEjQu3FSEcnF_vAMkr7sVYQ1odhQg0gT6MTWXvw41v7BkuaSvT3WGeDC7zHUdnC1gOA
  subject: mailto:admin@ecommerce.com

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: Chat-Notification-Service-API-docs
    serverUrl: http://localhost:${server.port}
    serverName: server dev
    title: Chat Notification Service API
    version: 1.0.0
    description: API document

logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.web.servlet.handler: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always