version: '3.8'
services:
  read-service:
    image: maianhhoang31072003/read-service:latest
    container_name: read-service
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8086:8086"


