version: '3.8'
services:
  payment-service:
    image: maianhhoang31072003/payment-service:latest
    container_name: payment-service
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8084:8084"


