version: '3.8'
services:
  review-service:
    image: maianhhoang31072003/review-service:latest
    container_name: review-service
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8087:8087"


